version: 2.1
orbs:
  heroku: circleci/heroku@0.0.5
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Execute test cases
          command: npm test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master